#!/bin/sh

# Script to launch a Stage simulation
# cd $HOME/

echo "Still under development..."

rm -r /home/fabrizio/.ros/log
roslaunch $(rospack find multi_robot_simulation)/launch/master_ext.launch
