int32 id
int32 state # see energy_mgmt/docking.h
int32 complex_state # see energy_mgmt/docking.h
int32 selected_ds #the id of the docking stationc currelty selected by the robot to recharge
float32 x    #robot x-coordinate (in the reference system of the sending robot, not in the one of the receiver)
float32 y    #robot y-coordinate (in the reference system of the sending robot, not in the one of the receiver)
